export const EVENTS = {
    APP_INIT: "APP_INIT",
    HIDE_LOADING: "HIDE_LOADING",

    MAP_SWITCHED: "MAP_SWITCHED",
    MAP_LOADED: "MAP_LOADED",
    MAPS_LOADED: "MAPS_LOADED",
    MAP_CLICKED: "MAP_CLICKED",
    MAP_SWITCH_REQUESTED: "MAP_SWITCH_REQUESTED",
    MAP_SWITCH_REQUEST_REJECTED: "MAP_SWITCH_REQUEST_REJECTED",
    NEW_MAP_LOADED: "NEW_MAP_LOADED",
    MAP_SAVE_STARTED: "MAP_SAVE_STARTED",
    MAP_SAVE_SUCCEEDED: "MAP_SAVE_SUCCEEDED",
    MAP_SAVE_FAILED: "MAP_SAVE_FAILED",
    MAP_SAVE_AVAILABILITY_CHANGED: "MAP_SAVE_AVAILABILITY_CHANGED",

    UI_ADD_NEW_MARKER_REQUEST: "UI_ADD_NEW_MARKER_REQUEST",
    UI_SWITCH_MAP_REQUEST: "UI_SWITCH_MAP_REQUEST",
    UI_COORDINATE_CHANGED: "UI_COORDINATE_CHANGED",
    UI_COLLAPSE_SHOW_STARTED: "UI_COLLAPSE_SHOW_STARTED",
    UI_COLLAPSE_HIDE_STARTED: "UI_COLLAPSE_HIDE_STARTED",
    UI_COLLAPSE_HIDDEN: "UI_COLLAPSE_HIDDEN",
    UI_COLLAPSE_CLOSE_REQUESTED: "UI_COLLAPSE_CLOSE_REQUESTED",
    UI_MAP_FILE_DROPPED: "UI_MAP_FILE_DROPPED",
    UI_EQUIRECTANGULAR_FILE_DROPPED: "UI_EQUIRECTANGULAR_FILE_DROPPED",
    UI_SAVE_MAP_CLICKED: "UI_SAVE_MAP_CLICKED",
    UI_ADD_NEW_MAP_REQUEST: "UI_ADD_NEW_MAP_REQUEST",
    UI_NORTH_DIRECTION_CHANGED: "UI_NORTH_DIRECTION_CHANGED",
    UI_EQUIRECTANGULAR_FULLSCREEN_REQUEST: "UI_EQUIRECTANGULAR_FULLSCREEN_REQUEST",
    UI_POINT_SAVE_REQUESTED: "UI_POINT_SAVE_REQUESTED",
    UI_CONNECTION_CREATE_REQUEST: "UI_CONNECTION_CREATE_REQUEST",

    EQUIRECTANGULAR_IMAGE_LOADED: "EQUIRECTANGULAR_IMAGE_LOADED",

    MARKER_PLACING_STARTED: "MARKER_PLACING_STARTED",
    MARKER_PLACING_CANCELLED: "MARKER_PLACING_CANCELLED",
    MARKER_CLICKED: "MARKER_CLICKED",
    MARKER_SELECTED: "MARKER_SELECTED",
    POINTS_LOADED: "POINTS_LOADED",
    NEW_MARKER_PLACED: "NEW_MARKER_PLACED",
    MARKER_MOVED: "MARKER_MOVED",
    POINT_DIRTY_STATE_CHANGED: "POINT_DIRTY_STATE_CHANGED",

    CONNECTIONS_LOADED: "CONNECTIONS_LOADED",
    NEW_CONNECTION_ADDED: "NEW_CONNECTION_ADDED",
    CONNECTION_MODE_CHANGED: "CONNECTION_MODE_CHANGED",
    CONNECTIONS_SAVED: "CONNECTIONS_SAVED",
    CONNECTION_LIST_UI_UPDATE: "CONNECTION_LIST_UI_UPDATE",
    UI_CONNECTION_HIGHLIGHT: "UI_CONNECTION_HIGHLIGHT",
    UI_CONNECTION_CENTER_VIEW: "UI_CONNECTION_CENTER_VIEW",

    TOAST_SHOW: "TOAST_SHOW",
    TOAST_HIDE_ID: "TOAST_HIDE_ID"
};

class EventBus extends EventTarget {
    emit(eventName, detail = {}) {
        this.dispatchEvent(new CustomEvent(eventName, { detail }));
    }

    on(eventName, listener) {
        listener._wrapped = (event) => listener(event.detail);
        this.addEventListener(eventName, listener._wrapped);
    }

    off(eventName, listener) {
        if (listener._wrapped) {
            this.removeEventListener(eventName, listener._wrapped);
        }
    }
}

export const eventBus = new EventBus();